// Catálogo de municipios de México por entidad federativa (INEGI/ENVIPE)
// Clave numérica → Nombre oficial
// Solo incluye municipios presentes en ENVIPE 2025

export const MUNICIPIOS = {
  1: { // Aguascalientes
    1: 'Aguascalientes', 2: 'Asientos', 3: 'Calvillo', 4: 'Cosío',
    5: 'Jesús María', 6: 'Pabellón de Arteaga', 7: 'Rincón de Romos',
    8: 'San José de Gracia', 9: 'Tepezalá', 10: 'El Llano', 11: 'San Francisco de los Romo',
  },
  2: { // Baja California
    1: 'Ensenada', 2: 'Mexicali', 3: 'Tecate', 4: 'Tijuana', 5: 'Playas de Rosarito',
  },
  3: { // Baja California Sur
    1: 'Comondú', 2: 'Mulegé', 3: 'La Paz', 8: 'Los Cabos', 9: 'Loreto',
  },
  4: { // Campeche
    1: 'Calkiní', 2: 'Campeche', 3: 'Carmen', 4: 'Champotón', 5: 'Hecelchakán',
    6: 'Hopelchén', 7: 'Palizada', 8: 'Tenabo', 9: 'Escárcega', 10: 'Calakmul', 11: 'Candelaria',
  },
  5: { // Coahuila
    1: 'Abasolo', 2: 'Acuña', 3: 'Allende', 4: 'Arteaga', 6: 'Candela',
    7: 'Castaños', 9: 'Cuatro Ciénegas', 10: 'Escobedo', 15: 'Francisco I. Madero',
    17: 'Frontera', 18: 'General Cepeda', 19: 'Guerrero', 20: 'Hidalgo',
    22: 'Jiménez', 24: 'Juárez', 25: 'Lamadrid', 27: 'Matamoros', 28: 'Monclova',
    30: 'Múzquiz', 32: 'Nava', 33: 'Ocampo', 35: 'Parras', 36: 'Piedras Negras',
  },
  6: { // Colima
    1: 'Armería', 2: 'Colima', 3: 'Comala', 4: 'Coquimatlán', 5: 'Cuauhtémoc',
    6: 'Ixtlahuacán', 7: 'Manzanillo', 8: 'Minatitlán', 9: 'Tecomán', 10: 'Villa de Álvarez',
  },
  7: { // Chiapas
    1: 'Acacoyagua', 2: 'Acala', 3: 'Acapetahua', 4: 'Altamirano', 5: 'Amatán',
    9: 'Arriaga', 12: 'Bejucal de Ocampo', 13: 'Bella Vista', 14: 'Berriozábal',
    15: 'Bochil', 16: 'El Bosque', 17: 'Cacahoatán', 19: 'Comitán de Domínguez',
    23: 'La Concordia', 27: 'Chiapa de Corzo', 31: 'Chicoasén', 32: 'Chicomuselo',
    37: 'Escuintla', 38: 'Francisco León', 40: 'Frontera Comalapa', 41: 'Frontera Hidalgo',
    43: 'La Grandeza', 47: 'Huehuetán', 48: 'Huixtán', 51: 'Ixtacomitán',
    52: 'Ixtapa', 53: 'Ixtapangajoya', 55: 'Jiquipilas', 57: 'Jitotol',
    59: 'Juárez', 61: 'Larráinzar', 65: 'Mapastepec', 67: 'Las Margaritas',
    68: 'Mazapa de Madero', 71: 'Metapa', 74: 'Mitontic', 77: 'Motozintla',
  },
  8: { // Chihuahua
    1: 'Ahumada', 2: 'Aldama', 3: 'Allende', 4: 'Aquiles Serdán', 5: 'Ascensión',
    6: 'Bachíniva', 7: 'Balleza', 8: 'Batopilas', 9: 'Bocoyna', 10: 'Buenaventura',
    11: 'Camargo', 12: 'Carichí', 13: 'Casas Grandes', 14: 'Chihuahua', 15: 'Chínipas',
    16: 'Delicias', 17: 'Dr. Belisario Domínguez', 18: 'Galeana', 19: 'Santa Isabel',
    21: 'Guachochi', 22: 'Guadalupe', 23: 'Guadalupe y Calvo', 24: 'Guazapares',
    25: 'Guerrero', 26: 'Hidalgo del Parral', 27: 'Huejotitán', 28: 'Ignacio Zaragoza',
    29: 'Janos', 30: 'Jiménez', 32: 'Juárez', 33: 'Julimes',
  },
  9: { // Ciudad de México
    2: 'Azcapotzalco', 3: 'Coyoacán', 4: 'Cuajimalpa', 5: 'Gustavo A. Madero',
    6: 'Iztacalco', 7: 'Iztapalapa', 8: 'La Magdalena Contreras', 9: 'Milpa Alta',
    10: 'Álvaro Obregón', 11: 'Tláhuac', 12: 'Tlalpan', 13: 'Xochimilco',
    14: 'Benito Juárez', 15: 'Cuauhtémoc', 16: 'Miguel Hidalgo', 17: 'Venustiano Carranza',
  },
  10: { // Durango
    1: 'Canatlán', 2: 'Canelas', 3: 'Coneto de Comonfort', 4: 'Cuencamé',
    5: 'Durango', 6: 'General Simón Bolívar', 7: 'Gómez Palacio', 8: 'Guadalupe Victoria',
    9: 'Guanaceví', 10: 'Hidalgo', 11: 'Indé', 12: 'Lerdo',
    13: 'Mapimí', 14: 'Mezquital', 15: 'Nazas', 16: 'Nombre de Dios',
    17: 'Ocampo', 18: 'El Oro', 19: 'Otáez', 20: 'Pánuco de Coronado',
    21: 'Peñón Blanco', 22: 'Poanas', 23: 'Pueblo Nuevo', 24: 'Rodeo',
    25: 'San Bernardo', 26: 'San Dimas', 27: 'San Juan de Guadalupe', 28: 'San Juan del Río',
    29: 'San Luis del Cordero', 30: 'San Pedro del Gallo', 31: 'Santa Clara',
    32: 'Santiago Papasquiaro', 33: 'Súchil', 34: 'Tamazula', 35: 'Tepehuanes',
    36: 'Tlahualilo', 37: 'Topia', 38: 'Vicente Guerrero',
  },
  11: { // Guanajuato
    1: 'Abasolo', 2: 'Acámbaro', 3: 'San Miguel de Allende', 4: 'Apaseo el Alto',
    5: 'Apaseo el Grande', 6: 'Atarjea', 7: 'Celaya', 8: 'Manuel Doblado',
    9: 'Comonfort', 10: 'Coroneo', 11: 'Cortazar', 12: 'Cuerámaro',
    13: 'Doctor Mora', 14: 'Dolores Hidalgo', 15: 'Guanajuato', 16: 'Huanímaro',
    17: 'Irapuato', 18: 'Jaral del Progreso', 19: 'Jerécuaro', 20: 'León',
    21: 'Moroleón', 22: 'Ocampo', 23: 'Pénjamo', 24: 'Pueblo Nuevo',
    25: 'Purísima del Rincón', 26: 'Romita', 27: 'Salamanca', 28: 'Salvatierra',
    29: 'San Diego de la Unión', 30: 'San Felipe', 31: 'San Francisco del Rincón',
    32: 'San José Iturbide', 33: 'San Luis de la Paz', 34: 'Santa Catarina',
    35: 'Santa Cruz de Juventino Rosas', 36: 'Santiago Maravatío', 37: 'Silao de la Victoria',
    38: 'Tarandacuao', 39: 'Tarimoro', 40: 'Tierra Blanca', 41: 'Uriangato',
    42: 'Valle de Santiago', 43: 'Victoria', 44: 'Villagrán', 45: 'Xichú', 46: 'Yuriria',
  },
  12: { // Guerrero
    1: 'Acapulco de Juárez', 2: 'Ahuacuotzingo', 3: 'Ajuchitlán del Progreso',
    4: 'Alcozauca de Guerrero', 5: 'Alpoyeca', 6: 'Apaxtla', 7: 'Arcelia',
    8: 'Atenango del Río', 9: 'Atlamajalcingo del Monte', 10: 'Atlixtac',
    11: 'Atoyac de Álvarez', 12: 'Ayutla de los Libres', 13: 'Azoyú',
    14: 'Benito Juárez', 15: 'Buenavista de Cuéllar', 16: 'Coahuayutla de José María Izazaga',
    17: 'Cocula', 18: 'Copala', 19: 'Copalillo', 20: 'Copanatoyac',
  },
  13: { // Hidalgo
    1: 'Acatlán', 2: 'Acaxochitlán', 3: 'Actopan', 4: 'Agua Blanca de Iturbide',
    5: 'Ajacuba', 6: 'Alfajayucan', 7: 'Almoloya', 8: 'Apan',
    9: 'El Arenal', 10: 'Atitalaquia', 11: 'Atlapexco', 12: 'Atotonilco el Grande',
    13: 'Atotonilco de Tula', 14: 'Calnali', 15: 'Cardonal', 16: 'Cuautepec de Hinojosa',
    17: 'Chapantongo', 18: 'Chapulhuacán', 19: 'Chilcuautla', 20: 'Eloxochitlán',
    21: 'Emiliano Zapata', 22: 'Epazoyucan', 23: 'Francisco I. Madero', 24: 'Huasca de Ocampo',
    25: 'Huautla', 26: 'Huazalingo', 27: 'Huehuetla', 28: 'Huejutla de Reyes',
    29: 'Huichapan', 30: 'Ixmiquilpan', 31: 'Jacala de Ledezma', 32: 'Jaltocán',
    33: 'Juárez Hidalgo', 34: 'Lolotla', 35: 'Metepec', 36: 'San Agustín Metzquititlán',
    37: 'Metztitlán', 38: 'Mineral del Chico', 39: 'Mineral del Monte', 40: 'La Misión',
    41: 'Mixquiahuala de Juárez', 42: 'Molango de Escamilla', 43: 'Nicolás Flores',
    44: 'Nopala de Villagrán', 45: 'Omitlán de Juárez', 46: 'San Felipe Orizatlán',
    47: 'Pacula', 48: 'Pachuca de Soto', 49: 'Pisaflores', 50: 'Progreso de Obregón',
    51: 'Mineral de la Reforma', 52: 'San Agustín Tlaxiaca', 53: 'San Bartolo Tutotepec',
    54: 'San Salvador', 55: 'Santiago de Anaya', 56: 'Santiago Tulantepec',
    57: 'Singuilucan', 58: 'Tasquillo', 59: 'Tecozautla', 60: 'Tenango de Doria',
    61: 'Tepeapulco', 62: 'Tepehuacán de Guerrero', 63: 'Tepeji del Río de Ocampo',
    64: 'Tepetitlán', 65: 'Tetepango', 66: 'Villa de Tezontepec', 67: 'Tezontepec de Aldama',
    68: 'Tianguistengo', 69: 'Tizayuca', 70: 'Tlahuelilpan', 71: 'Tlahuiltepa',
    72: 'Tlanalapa', 73: 'Tlanchinol', 74: 'Tlaxcoapan', 75: 'Tolcayuca',
    76: 'Tula de Allende', 77: 'Tulancingo de Bravo', 78: 'Xochiatipan', 79: 'Xochicoatlán',
    80: 'Yahualica', 81: 'Zacualtipán de Ángeles', 82: 'Zapotlán de Juárez',
    83: 'Zempoala', 84: 'Zimapán',
  },
  14: { // Jalisco
    1: 'Acatic', 2: 'Acatlán de Juárez', 3: 'Ahualulco de Mercado', 4: 'Amacueca',
    5: 'Amatitán', 6: 'Ameca', 7: 'San Juanito de Escobedo', 8: 'Arandas',
    9: 'El Arenal', 10: 'Atemajac de Brizuela', 11: 'Atengo', 12: 'Atenguillo',
    13: 'Atotonilco el Alto', 14: 'Atoyac', 15: 'Autlán de Navarro', 16: 'Ayotlán',
    17: 'Ayutla', 18: 'La Barca', 19: 'Bolaños', 20: 'Cabo Corrientes',
    39: 'Guadalajara', 70: 'Puerto Vallarta', 98: 'Tlaquepaque', 101: 'Tlajomulco de Zúñiga',
    102: 'Tonalá', 120: 'Zapopan', 124: 'Zapotlanejo',
  },
  15: { // Estado de México
    1: 'Acambay de Ruíz Castañeda', 2: 'Acolman', 3: 'Aculco', 4: 'Almoloya de Alquisiras',
    5: 'Almoloya de Juárez', 6: 'Almoloya del Río', 7: 'Amanalco', 8: 'Amatepec',
    9: 'Amecameca', 10: 'Apaxco', 11: 'Atenco', 12: 'Atizapán',
    13: 'Atizapán de Zaragoza', 14: 'Atlacomulco', 15: 'Atlautla', 16: 'Axapusco',
    17: 'Ayapango', 18: 'Calimaya', 19: 'Capulhuac', 20: 'Coacalco de Berriozábal',
    21: 'Coatepec Harinas', 22: 'Cocotitlán', 23: 'Coyotepec', 24: 'Cuautitlán',
    25: 'Chalco', 26: 'Chapa de Mota', 27: 'Chapultepec', 28: 'Chiautla',
    29: 'Chicoloapan', 30: 'Chiconcuac', 31: 'Chimalhuacán', 32: 'Donato Guerra',
    33: 'Ecatepec de Morelos', 34: 'Ecatzingo', 35: 'Huehuetoca', 36: 'Hueypoxtla',
    37: 'Huixquilucan', 38: 'Isidro Fabela', 39: 'Ixtapaluca', 40: 'Ixtapan de la Sal',
    41: 'Ixtapan del Oro', 42: 'Ixtlahuaca', 43: 'Xalatlaco', 44: 'Jaltenco',
    45: 'Jilotepec', 46: 'Jilotzingo', 47: 'Jiquipilco', 48: 'Jocotitlán',
    49: 'Joquicingo', 50: 'Juchitepec', 51: 'Lerma', 52: 'Malinalco',
    53: 'Melchor Ocampo', 54: 'Metepec', 55: 'Mexicaltzingo', 56: 'Morelos',
    57: 'Naucalpan de Juárez', 58: 'Nezahualcóyotl', 59: 'Nextlalpan', 60: 'Nicolás Romero',
    61: 'Nopaltepec', 62: 'Ocoyoacac', 63: 'Ocuilan', 64: 'El Oro',
    65: 'Otumba', 66: 'Otzoloapan', 67: 'Otzolotepec', 68: 'Ozumba',
    69: 'Papalotla', 70: 'La Paz', 71: 'Polotitlán', 72: 'Rayón',
    73: 'San Antonio la Isla', 74: 'San Felipe del Progreso', 75: 'San Martín de las Pirámides',
    76: 'San Mateo Atenco', 77: 'San Simón de Guerrero', 78: 'Santo Tomás',
    79: 'Soyaniquilpan de Juárez', 80: 'Sultepec', 81: 'Tecámac', 82: 'Tejupilco',
    83: 'Temamatla', 84: 'Temascalapa', 85: 'Temascalcingo', 86: 'Temascaltepec',
    87: 'Temoaya', 88: 'Tenancingo', 89: 'Tenango del Aire', 90: 'Tenango del Valle',
    91: 'Teoloyucan', 92: 'Teotihuacán', 93: 'Tepetlaoxtoc', 94: 'Tepetlixpa',
    95: 'Tepotzotlán', 96: 'Tequixquiac', 97: 'Texcaltitlán', 98: 'Texcalyacac',
    99: 'Texcoco', 100: 'Tezoyuca', 101: 'Tianguistenco', 102: 'Timilpan',
    103: 'Tlalmanalco', 104: 'Tlalnepantla de Baz', 105: 'Tlatlaya', 106: 'Toluca',
    107: 'Tonatico', 108: 'Tultepec', 109: 'Tultitlán', 110: 'Valle de Bravo',
    111: 'Villa de Allende', 112: 'Villa del Carbón', 113: 'Villa Guerrero',
    114: 'Villa Victoria', 115: 'Xonacatlán', 116: 'Zacazonapan', 117: 'Zacualpan',
    118: 'Zinacantepec', 119: 'Zumpahuacán', 120: 'Zumpango', 121: 'Cuautitlán Izcalli',
    122: 'Valle de Chalco Solidaridad', 123: 'Luvianos', 124: 'San José del Rincón',
    125: 'Tonanitla',
  },
  16: { // Michoacán
    1: 'Acuitzio', 2: 'Aguililla', 3: 'Álvaro Obregón', 4: 'Angamacutiro',
    5: 'Angangueo', 6: 'Apatzingán', 7: 'Aporo', 8: 'Aquila',
    9: 'Ario', 10: 'Arteaga', 11: 'Briseñas', 12: 'Buenavista',
    13: 'Carácuaro', 14: 'Coahuayana', 15: 'Coalcomán de Vázquez Pallares', 16: 'Coeneo',
    17: 'Contepec', 18: 'Copándaro', 19: 'Cotija', 20: 'Cuitzeo',
    21: 'Charapan', 22: 'Charo', 23: 'Chavinda', 24: 'Cherán',
    25: 'Chilchota', 26: 'Chinicuila', 27: 'Chucándiro', 28: 'Churintzio',
    29: 'Churumuco', 30: 'Epitacio Huerta', 31: 'Erongarícuaro', 32: 'Gabriel Zamora',
    33: 'Hidalgo', 34: 'La Huacana', 35: 'Huandacareo', 36: 'Huaniqueo',
    37: 'Huetamo', 38: 'Huiramba', 39: 'Indaparapeo', 40: 'Irimbo',
    41: 'Ixtlán', 42: 'Jacona', 43: 'Jiménez', 44: 'Jiquilpan',
    45: 'Juárez', 46: 'Jungapeo', 47: 'Lagunillas', 48: 'Madero',
    49: 'Maravatío', 50: 'Marcos Castellanos', 51: 'Lázaro Cárdenas', 52: 'Morelia',
    53: 'Moroleon', 54: 'Mugica', 55: 'Nahuatzen', 56: 'Nocupétaro',
    57: 'Nuevo Parangaricutiro', 58: 'Nuevo Urecho', 59: 'Numaran', 60: 'Ocampo',
    61: 'Pajacuarán', 62: 'Panindícuaro', 63: 'Parácuaro', 64: 'Paracho',
    65: 'Pátzcuaro', 66: 'Penjamillo', 67: 'Peribán', 68: 'La Piedad',
    69: 'Purépero', 70: 'Puruarán', 71: 'Queréndaro', 72: 'Quiroga',
    73: 'Cojumatlán de Régules', 74: 'Los Reyes', 75: 'Sahuayo', 76: 'San Lucas',
    77: 'Santa Ana Maya', 78: 'Salvador Escalante', 79: 'Senguio', 80: 'Susupuato',
    81: 'Tacámbaro', 82: 'Tancítaro', 83: 'Tangamandapio', 84: 'Tangancícuaro',
    85: 'Tanhuato', 86: 'Taretan', 87: 'Tarímbaro', 88: 'Tepalcatepec',
    89: 'Tingambato', 90: 'Tingüindín', 91: 'Tiquicheo de Nicolás Romero', 92: 'Tlalpujahua',
    93: 'Tlazazalca', 94: 'Tocumbo', 95: 'Tumbiscatío', 96: 'Turicato',
    97: 'Tuxpan', 98: 'Tuzantla', 99: 'Tzintzuntzan', 100: 'Tzitzio',
    101: 'Uruapan', 102: 'Venustiano Carranza', 103: 'Villamar', 104: 'Vista Hermosa',
    105: 'Yurécuaro', 106: 'Zacapu', 107: 'Zamora', 108: 'Zinapécuaro',
    109: 'Ziracuaretiro', 110: 'Zitácuaro', 111: 'José Sixto Verduzco',
  },
  17: { // Morelos
    1: 'Amacuzac', 2: 'Atlatlahucan', 3: 'Axochiapan', 4: 'Ayala',
    5: 'Coatlán del Río', 6: 'Cuautla', 7: 'Cuernavaca', 8: 'Emiliano Zapata',
    9: 'Huitzilac', 10: 'Jantetelco', 11: 'Jiutepec', 12: 'Jojutla',
    13: 'Jonacatepec de Leandro Valle', 14: 'Mazatepec', 15: 'Miacatlán', 16: 'Ocuituco',
    17: 'Puente de Ixtla', 18: 'Temixco', 19: 'Tepalcingo', 20: 'Tepoztlán',
    21: 'Tetecala', 22: 'Tetela del Volcán', 23: 'Tlalnepantla', 24: 'Tlaltizapán de Zapata',
    25: 'Tlaquiltenango', 26: 'Tlayacapan', 27: 'Totolapan', 28: 'Xochitepec',
    29: 'Yautepec', 30: 'Yecapixtla', 31: 'Zacatepec', 32: 'Zacualpan de Amilpas',
    33: 'Temoac',
  },
  18: { // Nayarit
    1: 'Acaponeta', 2: 'Ahuacatlán', 3: 'Amatlán de Cañas', 4: 'Compostela',
    5: 'Huajicori', 6: 'Ixtlán del Río', 7: 'Jala', 8: 'Xalisco',
    9: 'Del Nayar', 10: 'Rosamorada', 11: 'Ruíz', 12: 'San Blas',
    13: 'San Pedro Lagunillas', 14: 'Santa María del Oro', 15: 'Santiago Ixcuintla',
    16: 'Tecuala', 17: 'Tepic', 18: 'Tuxpan', 19: 'La Yesca', 20: 'Bahía de Banderas',
  },
  19: { // Nuevo León
    1: 'Abasolo', 2: 'Agualeguas', 3: 'Los Aldamas', 4: 'Allende',
    5: 'Anáhuac', 6: 'Apodaca', 7: 'Aramberri', 8: 'Bustamante',
    9: 'Cadereyta Jiménez', 10: 'El Carmen', 11: 'Cerralvo', 12: 'Ciénega de Flores',
    13: 'China', 14: 'Doctor Arroyo', 15: 'Doctor Coss', 16: 'Doctor González',
    17: 'Galeana', 18: 'García', 19: 'San Pedro Garza García', 20: 'General Bravo',
    21: 'General Escobedo', 22: 'General Terán', 23: 'General Treviño', 24: 'General Zaragoza',
    25: 'General Zuazua', 26: 'Guadalupe', 27: 'Los Herreras', 28: 'Higueras',
    29: 'Hualahuises', 30: 'Iturbide', 31: 'Juárez', 32: 'Lampazos de Naranjo',
    33: 'Linares', 34: 'Marín', 35: 'Melchor Ocampo', 36: 'Mier y Noriega',
    37: 'Mina', 38: 'Montemorelos', 39: 'Monterrey', 40: 'Parás',
    41: 'Pesquería', 42: 'Los Ramones', 43: 'Rayones', 44: 'Sabinas Hidalgo',
    45: 'Salinas Victoria', 46: 'San Nicolás de los Garza', 47: 'Hidalgo', 48: 'Santa Catarina',
    49: 'Santiago', 50: 'Vallecillo', 51: 'Villaldama',
  },
  20: { // Oaxaca
    1: 'Abejones', 2: 'Acatlán de Pérez Figueroa', 3: 'Asunción Cacalotepec', 4: 'Asunción Cuyotepeji',
    5: 'Asunción Ixtaltepec', 6: 'Asunción Nochixtlán', 7: 'Asunción Ocotlán', 8: 'Asunción Tlacolulita',
    67: 'Oaxaca de Juárez', 184: 'San Juan Bautista Tuxtepec', 385: 'Santa Cruz Xoxocotlán',
    399: 'Santa Lucía del Camino', 417: 'Santa María Atzompa', 528: 'Santo Domingo Tehuantepec',
  },
  21: { // Puebla
    1: 'Acajete', 2: 'Acateno', 3: 'Acatlán', 4: 'Acatzingo',
    5: 'Acteopan', 6: 'Ahuacatlán', 7: 'Ahuatlán', 8: 'Ahuazotepec',
    9: 'Ahuehuetitla', 10: 'Ajalpan', 11: 'Albino Zertuche', 12: 'Atzala',
    13: 'Atzitzihuacán', 14: 'Atzitzintla', 15: 'Axutla', 16: 'Ayotoxco de Guerrero',
    17: 'Calpan', 18: 'Caltepec', 19: 'Camocuautla', 20: 'Caxhuacan',
    106: 'Puebla', 114: 'San Andrés Cholula', 119: 'San Pedro Cholula',
    140: 'Tehuacán', 156: 'Teziutlán',
  },
  22: { // Querétaro
    1: 'Amealco de Bonfil', 2: 'Pinal de Amoles', 3: 'Arroyo Seco', 4: 'Cadereyta de Montes',
    5: 'Colón', 6: 'Corregidora', 7: 'Ezequiel Montes', 8: 'Huimilpan',
    9: 'Jalpan de Serra', 10: 'Landa de Matamoros', 11: 'El Marqués', 12: 'Pedro Escobedo',
    13: 'Peñamiller', 14: 'Querétaro', 15: 'San Joaquín', 16: 'San Juan del Río',
    17: 'Tequisquiapan', 18: 'Tolimán',
  },
  23: { // Quintana Roo
    1: 'Cozumel', 2: 'Felipe Carrillo Puerto', 3: 'Isla Mujeres', 4: 'Othón P. Blanco',
    5: 'Benito Juárez', 6: 'José María Morelos', 7: 'Lázaro Cárdenas', 8: 'Solidaridad',
    9: 'Tulum', 10: 'Bacalar', 11: 'Puerto Morelos',
  },
  24: { // San Luis Potosí
    1: 'Ahualulco', 2: 'Alaquines', 3: 'Aquismón', 4: 'Armadillo de los Infante',
    5: 'Cárdenas', 6: 'Catorce', 7: 'Cedral', 8: 'Cerritos',
    9: 'Cerro de San Pedro', 10: 'Ciudad del Maíz', 11: 'Ciudad Fernández', 12: 'Tancanhuitz',
    13: 'Ciudad Valles', 14: 'Coxcatlán', 15: 'Charcas', 16: 'Ebano',
    17: 'Guadalcázar', 18: 'Huehuetlán', 19: 'Lagunillas', 20: 'Matehuala',
    21: 'Mexquitic de Carmona', 22: 'Moctezuma', 23: 'Rayón', 24: 'Rioverde',
    25: 'Salinas', 26: 'San Antonio', 27: 'San Ciro de Acosta', 28: 'San Luis Potosí',
    29: 'San Martín Chalchicuautla', 30: 'San Nicolás Tolentino', 31: 'Santa Catarina',
    32: 'Santa María del Río', 33: 'Santo Domingo', 34: 'San Vicente Tancuayalab',
    35: 'Soledad de Graciano Sánchez', 36: 'Tamasopo', 37: 'Tamazunchale', 38: 'Tampacán',
    39: 'Tampamolón Corona', 40: 'Tamuín', 41: 'Tanlajás', 42: 'Tanquián de Escobedo',
    43: 'Tierranueva', 44: 'Vanegas', 45: 'Venado', 46: 'Villa de Arriaga',
    47: 'Villa de Guadalupe', 48: 'Villa de la Paz', 49: 'Villa de Ramos',
    50: 'Villa de Reyes', 51: 'Villa Hidalgo', 52: 'Villa Juárez', 53: 'Axtla de Terrazas',
    54: 'Xilitla', 55: 'Zaragoza', 56: 'Villa Zaragoza', 57: 'El Naranjo',
  },
  25: { // Sinaloa
    1: 'Ahome', 2: 'Angostura', 3: 'Badiraguato', 4: 'Concordia',
    5: 'Cosalá', 6: 'Culiacán', 7: 'Choix', 8: 'Elota',
    9: 'Escuinapa', 10: 'El Fuerte', 11: 'Guasave', 12: 'Mazatlán',
    13: 'Mocorito', 14: 'Rosario', 15: 'Salvador Alvarado', 16: 'San Ignacio',
    17: 'Sinaloa', 18: 'Navolato',
  },
  26: { // Sonora
    1: 'Aconchi', 2: 'Agua Prieta', 3: 'Alamos', 4: 'Altar',
    5: 'Arivechi', 6: 'Arizpe', 7: 'Atil', 8: 'Bacanora',
    9: 'Bacerac', 10: 'Bacoachi', 11: 'Bácum', 12: 'Banámichi',
    13: 'Baviácora', 14: 'Bavispe', 15: 'Benjamín Hill', 16: 'Caborca',
    17: 'Cajeme', 18: 'Cananea', 19: 'Carbó', 20: 'La Colorada',
    21: 'Cucurpe', 22: 'Cumpas', 23: 'Divisaderos', 24: 'Empalme',
    25: 'Etchojoa', 26: 'Fronteras', 27: 'Granados', 28: 'Guaymas',
    29: 'Hermosillo', 30: 'Huachinera', 31: 'Huásabas', 32: 'Huatabampo',
    33: 'Huépac', 34: 'Imuris', 35: 'Magdalena', 36: 'Mazatán',
    37: 'Moctezuma', 38: 'Naco', 39: 'Nácori Chico', 40: 'Nacozari de García',
    41: 'Navojoa', 42: 'Nogales', 43: 'Ónavas', 44: 'Opodepe',
    45: 'Oquitoa', 46: 'Pitiquito', 47: 'Puerto Peñasco', 48: 'Quiriego',
    49: 'Rayón', 50: 'Rosario', 51: 'Sahuaripa', 52: 'San Felipe de Jesús',
    53: 'San Javier', 54: 'San Luis Río Colorado', 55: 'San Miguel de Horcasitas',
    56: 'San Pedro de la Cueva', 57: 'Santa Ana', 58: 'Santa Cruz',
    59: 'Sáric', 60: 'Soyopa', 61: 'Suaqui Grande', 62: 'Tepache',
    63: 'Trincheras', 64: 'Tubutama', 65: 'Ures', 66: 'Villa Hidalgo',
    67: 'Villa Pesqueira', 68: 'Yécora',
  },
  27: { // Tabasco
    1: 'Balancán', 2: 'Cárdenas', 3: 'Centla', 4: 'Centro',
    5: 'Comalcalco', 6: 'Cunduacán', 7: 'Emiliano Zapata', 8: 'Huimanguillo',
    9: 'Jalapa', 10: 'Jalpa de Méndez', 11: 'Jonuta', 12: 'Macuspana',
    13: 'Nacajuca', 14: 'Paraíso', 15: 'Tacotalpa', 16: 'Teapa', 17: 'Tenosique',
  },
  28: { // Tamaulipas
    1: 'Abasolo', 2: 'Aldama', 3: 'Altamira', 4: 'Antiguo Morelos',
    5: 'Burgos', 6: 'Bustamante', 7: 'Camargo', 8: 'Casas',
    9: 'Ciudad Madero', 10: 'Cruillas', 11: 'Gómez Farías', 12: 'González',
    13: 'Güémez', 14: 'Guerrero', 15: 'Hidalgo', 16: 'Jaumave',
    17: 'Jiménez', 18: 'Llera', 19: 'Mainero', 20: 'El Mante',
    21: 'Matamoros', 22: 'Méndez', 23: 'Mier', 24: 'Miguel Alemán',
    25: 'Miquihuana', 26: 'Nuevo Laredo', 27: 'Nuevo Morelos', 28: 'Ocampo',
    29: 'Padilla', 30: 'Palmillas', 31: 'Reynosa', 32: 'Río Bravo',
    33: 'San Carlos', 34: 'San Fernando', 35: 'San Nicolás', 36: 'Soto la Marina',
    37: 'Tampico', 38: 'Tula', 39: 'Valle Hermoso', 40: 'Victoria',
    41: 'Villagrán', 42: 'Xicoténcatl',
  },
  29: { // Tlaxcala
    1: 'Amaxac de Guerrero', 2: 'Apetatitlán de Antonio Carvajal', 3: 'Atlangatepec',
    4: 'Atltzayanca', 5: 'Apizaco', 6: 'Calpulalpan', 7: 'El Carmen Tequexquitla',
    8: 'Cuapiaxtla', 9: 'Cuaxomulco', 10: 'Chiautempan', 11: 'Muñoz de Domingo Arenas',
    12: 'Españita', 13: 'Huamantla', 14: 'Hueyotlipan', 15: 'Ixtacuixtla de Mariano Matamoros',
    16: 'Ixtenco', 17: 'Mazatecochco de José María Morelos', 18: 'Contla de Juan Cuamatzi',
    19: 'Tepetitla de Lardizábal', 20: 'Sanctórum de Lázaro Cárdenas', 21: 'Nanacamilpa de Mariano Arista',
    22: 'Acuamanala de Miguel Hidalgo', 23: 'Natívitas', 24: 'Panotla',
    25: 'San Pablo del Monte', 26: 'Santa Cruz Tlaxcala', 27: 'Tenancingo',
    28: 'Teolocholco', 29: 'Tepeyanco', 30: 'Terrenate', 31: 'Tetla de la Solidaridad',
    32: 'Tetlatlahuca', 33: 'Tlaxcala', 34: 'Tlaxco', 35: 'Tocatlán',
    36: 'Totolac', 37: 'Ziltlaltépec de Trinidad Sánchez Santos', 38: 'Tzompantepec',
    39: 'Xaloztoc', 40: 'Xaltocan', 41: 'Papalotla de Xicohténcatl', 42: 'Xicohtzinco',
    43: 'Yauhquemehcan', 44: 'Zacatelco', 45: 'Benito Juárez', 46: 'Emiliano Zapata',
    47: 'Lázaro Cárdenas', 48: 'La Magdalena Tlaltelulco', 49: 'San Damián Texóloc',
    50: 'San Francisco Tetlanohcan', 51: 'San Jerónimo Zacualpan', 52: 'San José Teacalco',
    53: 'San Juan Huactzinco', 54: 'San Lorenzo Axocomanitla', 55: 'San Lucas Tecopilco',
    56: 'Santa Ana Nopalucan', 57: 'Santa Apolonia Teacalco', 58: 'Santa Catarina Ayometla',
    59: 'Santa Cruz Quilehtla', 60: 'Santa Isabel Xiloxoxtla',
  },
  30: { // Veracruz
    1: 'Acajete', 2: 'Acatlán', 3: 'Acayucan', 4: 'Actopan',
    5: 'Acula', 6: 'Acultzingo', 7: 'Camarón de Tejeda', 8: 'Alpatláhuac',
    9: 'Alto Lucero de Gutiérrez Barrios', 10: 'Altotonga', 11: 'Alvarado', 12: 'Amatitlán',
    13: 'Naranjos Amatlán', 14: 'Amatlán de los Reyes', 15: 'Angel R. Cabada', 16: 'La Antigua',
    17: 'Apazapan', 18: 'Aquila', 19: 'Astacinga', 20: 'Atlahuilco',
    30: 'Boca del Río', 193: 'Veracruz', 212: 'Xalapa',
  },
  31: { // Yucatán
    1: 'Abalá', 2: 'Acanceh', 3: 'Akil', 4: 'Baca',
    5: 'Bokobá', 6: 'Buctzotz', 7: 'Calotmul', 8: 'Cansahcab',
    9: 'Cantamayec', 10: 'Celestún', 11: 'Cenotillo', 12: 'Conkal',
    13: 'Cuncunul', 14: 'Cuzamá', 15: 'Chacsinkín', 16: 'Chankom',
    17: 'Chapab', 18: 'Chemax', 19: 'Chickxulub Pueblo', 20: 'Chichimilá',
    21: 'Chikindzonot', 22: 'Chocholá', 23: 'Chumayel', 24: 'Dzán',
    25: 'Dzemul', 26: 'Dzidzantún', 27: 'Dzilam de Bravo', 28: 'Dzilam González',
    29: 'Dzitás', 30: 'Dzoncauich', 31: 'Espita', 32: 'Halachó',
    33: 'Hocabá', 34: 'Hoctún', 35: 'Homún', 36: 'Huhí',
    37: 'Hunucmá', 38: 'Ixil', 39: 'Izamal', 40: 'Kanasín',
    41: 'Kantunil', 42: 'Kaua', 43: 'Kinchil', 44: 'Kopomá',
    45: 'Mama', 46: 'Maní', 47: 'Maxcanú', 48: 'Mayapán',
    49: 'Mérida', 50: 'Mocochá', 51: 'Motul', 52: 'Muna',
    53: 'Muxupip', 54: 'Opichén', 55: 'Oxkutzcab', 56: 'Panabá',
    57: 'Peto', 58: 'Progreso', 59: 'Quintana Roo', 60: 'Río Lagartos',
    61: 'Sacalum', 62: 'Samahil', 63: 'Sanahcat', 64: 'San Felipe',
    65: 'Santa Elena', 66: 'Seyé', 67: 'Sinanché', 68: 'Sotuta',
    69: 'Sucilá', 70: 'Sudzal', 71: 'Suma', 72: 'Tahdziu',
    73: 'Tahmek', 74: 'Teabo', 75: 'Tecoh', 76: 'Tekal de Venegas',
    77: 'Tekantó', 78: 'Tekax', 79: 'Tekit', 80: 'Tekom',
    81: 'Telchac Pueblo', 82: 'Telchac Puerto', 83: 'Temax', 84: 'Temozón',
    85: 'Tepakán', 86: 'Tetiz', 87: 'Teya', 88: 'Ticul',
    89: 'Timucuy', 90: 'Tinum', 91: 'Tixcacalcupul', 92: 'Tixkokob',
    93: 'Tixmehuac', 94: 'Tixpéhual', 95: 'Tizimín', 96: 'Tunkás',
    97: 'Tzucacab', 98: 'Uayma', 99: 'Ucú', 100: 'Umán',
    101: 'Valladolid', 102: 'Xocchel', 103: 'Yaxcabá', 104: 'Yaxkukul', 105: 'Yobaín',
  },
  32: { // Zacatecas
    1: 'Apozol', 2: 'Apulco', 3: 'Atolinga', 4: 'Benito Juárez',
    5: 'Calera', 6: 'Cañitas de Felipe Pescador', 7: 'Concepción del Oro', 8: 'Cuauhtémoc',
    9: 'Chalchihuites', 10: 'Fresnillo', 11: 'Trinidad García de la Cadena', 12: 'Genaro Codina',
    13: 'General Enrique Estrada', 14: 'General Francisco R. Murguía', 15: 'El Plateado de Joaquín Amaro',
    16: 'General Pánfilo Natera', 17: 'Guadalupe', 18: 'Huanusco', 19: 'Jalpa',
    20: 'Jerez', 21: 'Jiménez del Teul', 22: 'Juan Aldama', 23: 'Juchipila',
    24: 'Loreto', 25: 'Luis Moya', 26: 'Mazapil', 27: 'Melchor Ocampo',
    28: 'Mezquital del Oro', 29: 'Miguel Auza', 30: 'Momax', 31: 'Monte Escobedo',
    32: 'Morelos', 33: 'Moyahua de Estrada', 34: 'Nochistlán de Mejía', 35: 'Noria de Ángeles',
    36: 'Ojocaliente', 37: 'Pánuco', 38: 'Pinos', 39: 'Río Grande',
    40: 'Sain Alto', 41: 'El Salvador', 42: 'Sombrerete', 43: 'Susticacán',
    44: 'Tabasco', 45: 'Tepechitlán', 46: 'Tepetongo', 47: 'Teúl de González Ortega',
    48: 'Tlaltenango de Sánchez Román', 49: 'Valparaíso', 50: 'Vetagrande',
    51: 'Villa de Cos', 52: 'Villa García', 53: 'Villa González Ortega', 54: 'Villa Hidalgo',
    55: 'Villanueva', 56: 'Zacatecas', 57: 'Trancoso', 58: 'Santa María de la Paz',
  },
}

// Helper: obtener municipios de una entidad como array ordenado por nombre
export function getMunicipiosByEntidad(entidadId) {
  const municipios = MUNICIPIOS[entidadId] || {}
  return Object.entries(municipios)
    .map(([id, nombre]) => ({ id: Number(id), nombre }))
    .sort((a, b) => a.nombre.localeCompare(b.nombre))
}
